name: build
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Clone bfg9000
      uses: actions/checkout@v2
      with:
        repository: jimporter/bfg9000
        ref: mopack
        path: bfg9000
    - name: Install dependencies
      run: |
        sudo apt-get install ninja-build
        pushd bfg9000
        pip install .
        popd
        pip install codecov '.[test]'
    - name: Run tests
      run: |
        python setup.py test -q
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install '.[test]'
    - name: Run lint
      run: |
        python setup.py lint
